version: '3.9'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/src
    environment:
      - SECRET_KEY=qz27o8t5m9ocmufnafagnirm33ubc2sb
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://financial:strx4012@db:5432/postgres
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: financial
      POSTGRES_PASSWORD: strx4012
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: